spring:
 application:
   name: Config-Prod

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.netflix.discovery: 'DEBUG'
